### ISSUE TITLE
migro command not getting executed successfully.

### ISSUE THREAD

**Issue by sadashiv-sumasoft** [uploadcare/migro#108]
Hello,

I am using the python version 3.8.8 and pip version 20.2.3 and uploadcare-migro version 1.8.0.
When I enter the command in the command prompt `migro <account_public_key> <uuids_file_name>`. I am getting the following output

`Traceback (most recent call last):
  File "c:\users\sadashiv.sangale\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\sadashiv.sangale\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\sadashiv.sangale\AppData\Local\Programs\Python\Python38\Scripts\migro.exe\__main__.py", line 4, in <module>
  File "c:\users\sadashiv.sangale\appdata\local\programs\python\python38\lib\site-packages\migro\cli.py", line 37, in <module>
    signals = (signal.SIGHUP, signal.SIGTERM, signal.SIGINT)
AttributeError: module 'signal' has no attribute 'SIGHUP'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000022B5C11E520>`

Can you please let me know what am I doing wrong here?
Is this utility working for anyone?

**Comment by andrewshkovskii** [comment]
Hey. This is because of the Windows OS and `signal` support for Python on that OS. Which Windows version are you using?

Someone from Uploadcare will figure it out, but for now, you can try to run it in the Docker or Unix-based system. 
Or you can locally modify the source code at line https://github.com/uploadcare/migro/blob/master/migro/cli.py#L42

change line `except NotImplementedError:` to `except (AttributeError, NotImplementedError):`
