### ISSUE TITLE
Update docs to require Python 3.5.3

### ISSUE THREAD

**Issue by owenhoskins** [uploadcare/migro#3]
Hello, first off nice tool! I will be using this to migrate a large set of images to Uploadcare.

With Python 3.5 running `migro` or `migro <my public key> migro-test.txt` throws this error:

```
Traceback (most recent call last):
  File "/Users/owenhoskins/.pyenv/versions/3.5.0/bin/migro", line 7, in <module>
    from migro.cli import cli
  File "/Users/owenhoskins/.pyenv/versions/3.5.0/lib/python3.5/site-packages/migro/cli.py", line 22, in <module>
    from migro.uploader.worker import Uploader, Events
  File "/Users/owenhoskins/.pyenv/versions/3.5.0/lib/python3.5/site-packages/migro/uploader/worker.py", line 16, in <module>
    from migro.uploader.utils import request
  File "/Users/owenhoskins/.pyenv/versions/3.5.0/lib/python3.5/site-packages/migro/uploader/utils.py", line 12, in <module>
    from aiohttp import ClientSession, TCPConnector
  File "/Users/owenhoskins/.pyenv/versions/3.5.0/lib/python3.5/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import *  # noqa
  File "/Users/owenhoskins/.pyenv/versions/3.5.0/lib/python3.5/site-packages/aiohttp/client.py", line 15, in <module>
    from . import connector as connector_mod
  File "/Users/owenhoskins/.pyenv/versions/3.5.0/lib/python3.5/site-packages/aiohttp/connector.py", line 11, in <module>
    from . import hdrs, helpers
  File "/Users/owenhoskins/.pyenv/versions/3.5.0/lib/python3.5/site-packages/aiohttp/helpers.py", line 22, in <module>
    from async_timeout import timeout
  File "/Users/owenhoskins/.pyenv/versions/3.5.0/lib/python3.5/site-packages/async_timeout/__init__.py", line 5, in <module>
    from typing import Optional, Type
ImportError: cannot import name 'Type'
```

I found this issue https://github.com/aio-libs/async-timeout/issues/38 and it seems that "Old versions have been dropped, the minimally supported python is 3.5.3". Shall I submit a PR to update the docs?

**Comment by andrewshkovskii** [comment]
Hello, Owen.

This tool will help you to migrate files from web to your Uploadcare account.
But notice that our UPLOAD API has slightly changed and now `from_url` API endpoint has  rate limit of `200req / min`.

I will look at the problem today and will let you know about our PR or will fix it by myself.
Thanks!

**Comment by andrewshkovskii** [comment]
You can check latest commits. 
(Especially https://github.com/uploadcare/migro/commit/d8d4e45d69c7b68c23db04a10e0b92b5dd462a7f )

Hope this will help.
