### ISSUE TITLE
Doesn't work on python 3.7

### ISSUE THREAD

**Issue by purge** [uploadcare/migro#4]
```
Traceback (most recent call last):
  File "/usr/local/bin/migro", line 7, in <module>
    from migro.cli import cli
  File "/usr/local/lib/python3.7/site-packages/migro/cli.py", line 22, in <module>
    from migro.uploader.worker import Uploader, Events
  File "/usr/local/lib/python3.7/site-packages/migro/uploader/worker.py", line 16, in <module>
    from migro.uploader.utils import request
  File "/usr/local/lib/python3.7/site-packages/migro/uploader/utils.py", line 12, in <module>
    from aiohttp import ClientSession, TCPConnector
  File "/usr/local/lib/python3.7/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import *  # noqa
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 15, in <module>
    from . import connector as connector_mod
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 11, in <module>
    from . import hdrs, helpers
  File "/usr/local/lib/python3.7/site-packages/aiohttp/helpers.py", line 29
    ensure_future = asyncio.async
                                ^
SyntaxError: invalid syntax
```

**Comment by andrewshkovskii** [comment]
Hello.
We haven't tested `migro` for python 3.7 yet.
You can switch to 3.5.3 while we fixing this bug.
Thanks.
